server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: users-status-check
          uri: lb://user-ms
          predicates:
            - Path=/user-ms/api/users/status/check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-ms/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: save-photo
          uri: lb://photo-ms
          predicates:
            - Path=/photo-ms/photo
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/photo-ms/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: user-ms-signup
          uri: lb://user-ms
          predicates:
            - Path=/user-ms/api/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-ms/(?<segment>.*), /$\{segment}
        - id: users-ms-login
          uri: lb://user-ms
          predicates:
            - Path=/user-ms/api/auth
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-ms/(?<segment>.*), /$\{segment}

        - id: users-ms-get-update-delete
          uri: lb://user-ms
          predicates:
            - Path=/api/users/**
            - Method=GET,PUT,DELETE
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-ms/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: get-user-photo
          uri: lb://photo-ms
          predicates:
            - Path=/photo-ms/photo/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/photo-ms/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: user-ms-actuator
          uri: lb://user-ms
          predicates:
            - Path=/user-ms/actuator/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-ms/(?<segment>.*), /$\{segment}
token:
  secret: Zuu-^@?eEpx@pg8j%Dj3W6rAEZm@44=JgcWJE$3pn_eUjA2s
management:
  endpoints:
    web:
      exposure:
        include: beans,health,routes,httptrace,gateway