server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-status-check
          uri: lb://user-ms
          predicates:
            - Path=/api/users/status/check
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true