server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users-status-check
          uri: lb://user-ms
          predicates:
            - Path=/api/users/status/check
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
        #another route
        - id: users-ms
            uri: lb://user-ms
            predicates:
              - Path=user-ms/api/users
              - Method=POST
            filters:
              - RemoveRequestHeader=Cookie
        #another route
        - id: users-ms-login
            uri: lb://user-ms
            predicates:
              - Path=user-ms/api/auth
              - Method=GET
            filters:
              - RemoveRequestHeader=Cookie
        #another route
        - id: users-ms-get-update-delete
            uri: lb://user-ms
            predicates:
              - Path=/api/users/**
              - Method=GET,PUT,DELETE
              - Header=Authorization, Bearer (.*)
            filters:
              - RemoveRequestHeader=Cookie
              - AuthorizationHeaderFilter